name: Production Tag Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install pnpm (as it's required for your project)
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Step 3: Pull Vercel Environment with Token
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Step 4: Install dependencies with pnpm
      - name: Install dependencies with pnpm
        run: pnpm install

      # Step 5: Build Project
      - name: Build Project
        run: vercel build --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
